#include "prefix/prefix.h"

#include "data-mov/mov.h"
#include "data-mov/xchg.h"
#include "data-mov/movext.h"
#include "data-mov/cltd.h"
#include "data-mov/lods.h"
#include "data-mov/lgdt.h"

#include "arith/adc.h"
#include "arith/add.h"
#include "arith/cmp.h"
#include "arith/dec.h"
#include "arith/inc.h"
#include "arith/neg.h"
#include "arith/imul.h"
#include "arith/mul.h"
#include "arith/idiv.h"
#include "arith/div.h"
#include "arith/sbb.h"
#include "arith/sub.h"

#include "control/jmp.h"
#include "control/jbe.h"
#include "control/ja.h"
#include "control/je.h"
#include "control/jne.h"
#include "control/jg.h"
#include "control/jge.h"
#include "control/js.h"
#include "control/jns.h"
#include "control/jl.h"
#include "control/jle.h"
#include "control/call.h"
#include "control/leave.h"
#include "control/push.h"
#include "control/pop.h"
#include "control/ret.h"

#include "logic/and.h"
#include "logic/or.h"
#include "logic/not.h"
#include "logic/xor.h"
#include "logic/sar.h"
#include "logic/shl.h"
#include "logic/shr.h"
#include "logic/shrd.h"
#include "logic/test.h"
#include "logic/setne.h"
#include "logic/sete.h"
#include "logic/std.h"
#include "logic/cld.h"

#include "string/rep.h"
#include "string/scas.h"
#include "string/stos.h"
#include "string/movs.h"

#include "misc/misc.h"

#include "special/special.h"

